### ISSUE TITLE
Questions about tissue regions

### ISSUE THREAD

**Issue by cf98** [zijianni/SpotClean#12]
Hi SpotClean developers,

Thank you for contributing this great tool to the community.

I have a question about the tissue regions.

In the `tissue_positions.csv` file from SpaceRanger output, it has a column that indicates whether the spot is in tissue or not.
However, this region is predefined by the user in Loupe Browser. Sometimes, we see folds on the tissue, and we exclude these regions. The fold regions will still have a lot of reads, but not marked as in tissue in the `tissue_positions.csv` file. Since the spotclean model takes information of the regions outside the tissue, do I need to manually include these fold regions to get more accurately cleaned spots?

Thanks,
Changfeng

**Comment by zijianni** [comment]
Hi Changfeng,

Thanks for your interests in using SpotClean! You've raised a good point that there could be unwanted tissue spots due to tissue folds. You can consider removing these spots *after* applying SpotClean since the tissue folds also naturally contribute to spot swapping across the slide. Including them during SpotClean should lead to more accurate estimation.

In my perspective, tissue folds should still be classified as tissue rather than background. You can further annotate them to be e.g. unwanted tissue spots and use it to further filter the spots.

**Comment by cf98** [comment]
> Hi Changfeng,
> 
> Thanks for your interests in using SpotClean! You've raised a good point that there could be unwanted tissue spots due to tissue folds. You can consider removing these spots _after_ applying SpotClean since the tissue folds also naturally contribute to spot swapping across the slide. Including them during SpotClean should lead to more accurate estimation.
> 
> In my perspective, tissue folds should still be classified as tissue rather than background. You can further annotate them to be e.g. unwanted tissue spots and use it to further filter the spots.

Thank you!
