### ISSUE TITLE
Questions about the output

### ISSUE THREAD

**Issue by cf98** [zijianni/SpotClean#13]
Hi SpotClean developers,

Can I ask another question about the output?

Since the default parameter for SpotClean will work on highly expressed and highly variable genes, the decontaminated objects will only contain those highly expressed genes. Would you suggest only keeping these genes for downstream analysis, or also try to include lowly expressed genes?

Thanks!

**Comment by zijianni** [comment]
The main reason we only decontamiate highly expressed and highly variable genes is that the other lowly expressed genes are too sparse to make any reliable inference. However, I think the SpotClean output matrix also contains those lowly expressed genes, but they are simply up-scaled based on the proportion of background UMI counts rather than estimated by SpotClean model.

For downstream analyses, it's pretty common to only use highly expressed and highly variable genes due to the same reason - low expression leads to high sparsity, and low variable indicates less useful information. I would recommend to start with the SpotClean output (which should contain both highly expressed and lowly but non-zero expressed genes), and check the guidance on specific downstream methods you want to use to determine whether or not to only use highly expressed and highly variable genes.
