### ISSUE TITLE
could spotclean work under situation that all spot 's tissue==1? that my ST data 's tissue position csv 's tissue is all 1,no o,that no backgroud spot

### ISSUE THREAD

**Issue by hwbdhuidhcoi** [zijianni/SpotClean#16]

**Comment by hwbdhuidhcoi** [comment]
@zijianni

**Comment by zijianni** [comment]
Hello, in that case SpotClean won't work since it can't tell whether the observed expressions in tissue spots are real or contaminated without the help of background spots. 

If you slides were fully covered by tissue, i.e. all spots on the slides are tissue spots, then unfortunately SpotClean can't help. If you are using a filtered data where the background spots have been removed, please go back and use the un-filtered raw data from SpaceRanger output.

**Comment by hwbdhuidhcoi** [comment]
蟹蟹 @zijianni
