### ISSUE TITLE
The tissue photographs were presented in the wrong horizontal and vertical ratio

### ISSUE THREAD

**Issue by BourbonZhang** [zijianni/SpotClean#20]
hi zijian,
i need some help.

when i use the visualize such as visualizeSlide(slide_obj) or visualizeLabel(slide_obj,"tissue"). The tissue photographs were presented in the wrong horizontal and vertical ratio. And the Loupe showed a normal scale. what should i do.

Thanks

**Comment by zijianni** [comment]
Hi @BourbonZhang ,

Can you show some example plot here, if not confidential? 

Based on your description, my suspicion is that the scale factors are not properly specified. There is a `scalefactors_json.json` file from SpaceRanger output specifying how the tissue image should be scaled in order to match the spot locations. You might want to play with it to see if that could fix the issue.

**Comment by zijianni** [comment]
Closing as no further communications
