### ISSUE TITLE
Pixel removal issue

### ISSUE THREAD

**Issue by JihyunKiminGithub** [zijianni/SpotClean#4]
Dear spotclean developers,

Hello!
When I use spotclean with multiple visium samples, some samples still keep most of the pixel.
But for my half of visium samples, almost 1/3 of pixels are removed..
This problem is kept even when I used different options (kernal and gene cutoff) while running spot clean.

I want to know what caused this situation. Is this only due to my low-quality visium? or Is there anyway that I can keep most of the pixel even after use of spotclean?

Thank you,
Jihyun

**Comment by zijianni** [comment]
Hi @JihyunKiminGithub , thanks for using our package! When you said "pixel", do you mean "spot" in our term (columns in the gene expression matrix), or image pixel of the H&E tissue image? 

If it's the former case, the only place we remove spots are removing background spots (spots not covered by tissue) after SpotClean decontamination. Our assumption is that background spots should not express any gene, and the observed expression in background spots in your raw data matrix are due to spot swapping contamination. So after decontamination, background spots have no gene expression, and there is no need to keep them. The number of background spots were determined by the size of your tissue section. If you have a small tissue, then you have more background spots, which will all be removed after decontamination.

If it's the latter case, our package does nothing about the H&E image files. I will appreciate it if you could provide more details.

**Comment by JihyunKiminGithub** [comment]
It was my mistake that some *spots* are removed after spotclean

Thank you for making this tool.

Best,
Jihyun
